version: "3.8"
services:
    python:
        image: "ghcr.io/game-on-paper-app/saiemgilani/gop-python"
        build: 
            context: ./python
            dockerfile: Dockerfile
        expose: 
            - 7000
    frontend:
        image: "ghcr.io/game-on-paper-app/saiemgilani/gop-frontend"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - python
        links:
            - python
        environment: 
            PORT: 8000
            RDATA_BASE_URL: "http://python:7000"
            NODE_DEBUG: "[frontend]"