name: deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js service
        uses: actions/setup-node@v1
      - name: Publish to GitHub Packages Registry [Python]
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: saiemgilani/game-on-paper-app/gop-frontend
          registry: gchr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./python/Dockerfile
          tags: latest
      - name: Publish to GitHub Packages Registry [Frontend]
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: saiemgilani/game-on-paper-app/gop-frontend
          registry: gchr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./frontend/Dockerfile
          tags: latest
      - name: Deploy package to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
            GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login gchr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull gchr.io/saiemgilani/game-on-paper-app/gop-python:latest
            docker pull gchr.io/saiemgilani/game-on-paper-app/gop-frontend:latest
            docker compose run -p 8000:8000 gchr.io/saiemgilani/game-on-paper-app/gop-frontend:latest  
